### ISSUE TITLE
gif in README doesn't show up in Chrome

### ISSUE THREAD

**Issue by finneycanhelp** [RxSwiftCommunity/RxSnippets#2]
I noticed that https://github.com/RxSwiftCommunity/RxSnippets/blob/master/assets/snippets.gif doesn't show correctly in the Chrome browser, but it does in Safari.

Therefore, the "Demo" works in Safari, but not in the Chrome browser. https://github.com/RxSwiftCommunity/RxSnippets

**Comment by carlosypunto** [comment]
Hi @finneycanhelp. ;-)  It's strange. For me works in both

**Comment by finneycanhelp** [comment]
ok. It's working for me on Chrome now that I am home. Perhaps it was a strange proxy issue or something. Thanks
